name: Dependencies

on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

  workflow_dispatch:

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.ACCESS_TOKEN }}
          config: .github/dependencies.yml
